### PR TITLE
Get Apple user first & last name from `self.data`

### PR DESCRIPTION
**Pull request by yuekui**
## Proposed changes

Decoded `id_token` doesn't contain name info, so we have to get such info from `self.data`

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Solves #482 #501

### CODE REVIEW

**Comment by mbaechtold** [comment]
Thanks for tackling the issue #482, @yuekui  👍

**Comment by alexislg2** [comment]
Thank you. Is is planned to merge this PR?

**Comment by yuekui** [comment]
> Thank you. Is is planned to merge this PR?

Yeah, I hope @omab could help 🤝

**Comment by timabbott** [comment]
@omab any chance you can review and merge this PR?  Apple will reject any app submitted connecting to a server without this change (because they require importing the change), so Apple authentication is currently broken without this PR.

**Comment by mbaechtold** [comment]
@yuekui, what coul we do about the failing checks reported by the Travis CI integration?

**Comment by yuekui** [comment]
> @yuekui, what could we do about the failing checks reported by the Travis CI integration?

#515 would fix the failed cases, we could simply wait or just sync with that branch

**Comment by mbaechtold** [comment]
#515 has been merged. Could you please rebase onto the latest main branch, @yuekui ?

**Comment by mbaechtold** [comment]
Awesome! Thanks to everyone! 😃

**Comment by mateuszmandera** [comment]
Thanks! When is the next release expected?

**Comment by yuekui** [comment]
Hi @nijel any chance we could have a new release with this patch?

**Pull request merged**
