### PR TITLE
Allow per-backend user pipeline settings

### PR DESCRIPTION
**Pull request by dehnert**
According to https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html, "All settings can be defined per-backend by adding the backend name to the setting name, like SOCIAL_AUTH_TWITTER_LOGIN_URL". This changes user.py to actually use per-backend settings for options like USERNAME_IS_FULL_EMAIL.

Note that get_username is always called with a backend, but user_details isn't, so a different version of `setting' is needed for the two.

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [X?] Lint and unit tests pass locally with my changes -- running tox reports an error in test_dummy both before and after my change
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by dehnert** [comment]
I'm confused that CI appears to have still not run.

**Comment by nijel** [comment]
Can you please prepare a matching pull request for the documentation? https://github.com/python-social-auth/social-docs/

**Comment by dehnert** [comment]
I think this change just makes the code match the already-existing documentation -- see https://github.com/python-social-auth/social-docs/blame/master/docs/configuration/settings.rst#L18, "All settings can be defined per-backend". Can you clarify what you're looking for in terms of doc changes?

**Comment by dehnert** [comment]
I'm still running with this patch on one of my sites -- it looks like this PR has a conflict now, but (glancing at the conflict) it doesn't look hard to resolve, or like the conflict is from this issue having been fixed. I can go back and update this PR, but @nijel , can you elaborate on what you were looking for in terms of added docs, so I can resolve that too?

**Comment by nijel** [comment]
I most likely missed your previous reply, it indeed seems that this PR makes it match the documentation.

**Comment by dehnert** [comment]
I've rebased, if you want to take a look and maybe merge it.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
