### PR TITLE
Introduce isort

### PR DESCRIPTION
**Pull request by nijel**
## Proposed changes

This builds on top of #643 and adds [isort](https://pycqa.github.io/isort/).

* Is there general interest in introducing such formatting into CI?
* It currently uses default configuration, not sure if it is the best fit

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Review by atodorov — CHANGES_REQUESTED** [review]
- Depends on #643 
- Needs isort check as part of CI, for example see https://github.com/kiwitcms/Kiwi/blob/master/.github/workflows/lint.yml#L102

**Comment by nijel** [comment]
pre-commit.ci does run the check as part of CI (it just needs to be enabled on the organization)

**Comment by atodorov** [comment]
> pre-commit.ci does run the check as part of CI (it just needs to be enabled on the organization)

I don't know what that means. Can you explain or post an example?

**Comment by nijel** [comment]
@atodorov https://pre-commit.ci runs it. It even can apply fixes to the open pull requests.

For example, see https://github.com/WeblateOrg/weblate/pull/6950, https://github.com/WeblateOrg/weblate/pull/6950/commits/4a440dfe6f9fac569ab77d72d58ee4e3fb5b9f0b is fixing commit generated by https://results.pre-commit.ci/run/github/3559019/1639521518.r-u4Pw1eSqSW13cfnzIvWQ

**Pull request merged**
