### PR TITLE
pre-commit autoupdate

### PR DESCRIPTION
**Pull request by cclauss**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers
why we should accept this pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue.

This pull request was made by running:
```
pre-commit autoupdate
pre-commit run --all-files
```

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Build-related changes (build process, tests runner, etc)  `pre-commit autoupdate`
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [x] pre-commit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by nijel** [comment]
I wanted to automate this by https://pre-commit.ci/, but this service can be only enabled by @omab

**Comment by cclauss** [comment]
Big thumbs up to pre-commit.ci -- Works GREAT.

**Comment by cclauss** [comment]
Unclear why flake8 passes on `pre-commit run --all-files` but fails on GitHub Actions.  I am unclear what the syntax `.github/matchers/flake8.json"` does.

**Comment by nijel** [comment]
> Unclear why flake8 passes on `pre-commit run --all-files` but fails on GitHub Actions.

Because it running a different version and different plugins? See https://github.com/python-social-auth/social-core/blob/master/.github/workflows/flake8.yml

> I am unclear what the syntax `.github/matchers/flake8.json"` does.

It allows GitHub to display reported issues, see https://fusectore.dev/2021/11/19/github-action-problem-matchers.html

Anyway, this PR has IMHO grown too much, I'd rather see it split it up. And we should have an approval from other maintainers before changing code-style and introducing black.

**Comment by cclauss** [comment]
Closing in favor of #700 which covers the essential issues.

**Pull request closed without merging**
