### PR TITLE
Add Keycloak backend with tests

### PR DESCRIPTION
**Pull request by aleksihakli**
This patchset adds a Keycloak OAuth 2.0 backend based on the Keycloak OpenID Connect 1.0 API.

### CODE REVIEW

**Comment by aleksihakli** [comment]
It seems like this patch set fails builds on Python 3.3 because Cryptography is not installed in the Tox build environment. [Python 3.3 is EOL](https://www.python.org/download/releases/3.3.0/) and could be deprecated.

**Comment by aleksihakli** [comment]
Hey @omab! Could this be merged into upstream?

**Comment by aleehedl** [comment]
Works well. Hoping to see this merged as soon as possible.

**Comment by lukaszlacinski** [comment]
Keycloak is an OIDC IdP. Why does the backend subclass BaseOAuth2 instead of OpenIdConnectAuth?

**Comment by aleksihakli** [comment]
We needed a authentication of users, and in our case OAuth 2.0 offered that with some customizations. Due to that I went with a KISS approach, just subclassing the OAuth 2.0 authentication, which produced less code and complexity, and appears to work well in the specific use case. OIDC 1.0 is, after all, based on the OAuth 2.0 protocol.

It is possible to implement OIDC 1.0 support as well, if there is a need and an ask for that.

**Comment by omab** [comment]
The change looks great, I might use it as an example in the future when properly documenting how to contribute backends.

Sorry about the delay on merging it.

**Comment by aleksihakli** [comment]
Great to have it upstream :) I'll see about contributing the OIDC backend as well, would be neat to have the full implementation available.

**Pull request merged**
