### PR TITLE
New backend for the WLCG IAM testing site

### PR DESCRIPTION
**Pull request by maikenp**
## Proposed changes

Adding the WLCG IAM backend testing site. 

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

I have tested using this backend with a local galaxy server. I can get id_token, access_token and refresh_token and things seem to work as expected.

### CODE REVIEW

**Comment by maikenp** [comment]
Hi, how can I fix the checks?

**Comment by nijel** [comment]
Can you please add tests for the backend?

**Comment by maikenp** [comment]
> Can you please add tests for the backend?

Thanks for your comment. 
There is little documentation on how you want those tests to be. What tests do you want, and in what way? 
Is there an example of a backend test that I could follow?

**Comment by nijel** [comment]
One of OAuth2 tests can be found here: https://github.com/python-social-auth/social-core/blob/master/social_core/tests/backends/test_digitalocean.py

**Comment by maikenp** [comment]
> Can you please add tests for the backend?

Hi, I have added a test, but not sufficient according to the codecov test. Could you give me some more guidance how to proceed?

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
