### PR TITLE
WIP: Added Auth0 provider

### PR DESCRIPTION
**Pull request by alesrosina**
Hi all, this is my first submission - I wanted to add  provider for Auth0, which I will need in an existing app called Weblate (http://weblate.org). I think it makes sense to make a contribution here, since it might be useful also for others.

Code is actually from: https://auth0.com/docs/quickstart/webapp/django/01-login

PS: This is my first contact with Django framework, so I'm not really 100% confident if I did all correct.

### CODE REVIEW

**Comment by alesrosina** [comment]
@omab would you be so kind to review it?

**Comment by omab** [comment]
@alesrosina, the code looks good to me, thanks for adding the changelog entry as well. There's any chance you can include tests for this backend? Thanks!

**Comment by alesrosina** [comment]
@omab hey, i am actually struggling to do it, since this is my first contact with django and python, so I'm not sure how to write or even run tests locally for this package.

Can you help me out here and write a decent test for it?

**Comment by alesrosina** [comment]
@omab I've added one more function to it, since I just realised, Auth0 is also offering additional parameters with auth path.

Can you look one more time and help me out with tests?

**Comment by alesrosina** [comment]
@omab I would actually appreciate if you could help me out here, since I would need this functionality quite soon in our solution.

**Comment by omab** [comment]
@alesrosina, I've added the test case for this backend. PR merged. Thanks!

**Comment by alesrosina** [comment]
Perfect, thanks for this! Will you also release new version, so I will be able to use this via `pip`? 

And thanks again!

**Comment by alesrosina** [comment]
@omab by the way, somehow one function got sliped out from master:

```py
    def auth_extra_arguments(self):
        """Return extra arguments needed on request-token process"""
        return self.setting('AUTH_EXTRA_ARGUMENTS', {})
```

Can you add it to `social_core/backends/auth0.py` or should I create one more pull request?

**Comment by omab** [comment]
@alesrosina, version `3.1.0` released

**Comment by alesrosina** [comment]
@omab perfect, thanks. Now I have another issue - when using it in my app, I do get an error:
```
File "/opt/app-root/lib/python3.5/site-packages/social_core/backends/auth0.py", line 5, in <module>
  from jose import jwt
ImportError: No module named 'jose'
```
In my app I've added it in `requirements.txt` as 
```
social-auth-core>=3.1.0
social-auth-app-django>=3.1.0
```

What am I doing wrong? Other providers work fine. Did I miss sth when I contributed here?

**Comment by omab** [comment]
@alesrosina, in order to use any jwt-related backend, you need to install `python-social-auth` with the `openidconnect` extra:

```shell
pip install social-auth-core[openidconnect]
```

**Comment by alesrosina** [comment]
Perfect, thank you very much! It works now!

**Pull request merged**
