### PR TITLE
Allow the OIDC backend to get user data/details from attributes

### PR DESCRIPTION
**Pull request by slyngshede**
Allow the OIDC backend to locate user data in "attributes", if that's where the server puts them.

## Proposed changes

I tried looking of a option that would allow the OIDC backend for get user details from
other places than directly in the response. Having the user details directly in the response
appears to be a legacy feature, at least according to https://apereo.github.io/cas/6.6.x/authentication/OIDC-Authentication-Claims.html.

Instead this patch will use the user data to request the data, but note that it's expect to
be in "attributes" and not as key directly in the response.

I have attempted to preserve the current functionality.

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by davidhalter** [comment]
Can you please show where in the OIDC spec these `attributes` are defined? I wasn't able to find it. I also fail to see where in the `Apereo CAS` docs it's mentioned that they have an `attributes` object.

**Comment by slyngshede** [comment]
I don't think it necessarily and OIDC thing and CAS doesn't document it. The response that's returned for the USERINFO_URL looks like this:

```
{
    'access_token': 'xxxxxxxxxxxxxxxxxxxx', 
    'id_token': 'yyyyyyyyyyyyyyyyyyyy',
    'token_type': 'Bearer', 
    'expires_in': 28800, 
    'scope': 'groups email openid profile', 
    'sub': 'Username', 
    'service': 'https://dev-server/complete/oidc/', 
    'auth_time': 1674822029, 
    'attributes': {
        'name': 'User',
        'groups': ['ops', 'dev', 'users']
        'preferred_username': 'slyngshede', 
        'email': 'user@example.org'
    }, 
    'id': 'User', 
    'client_id': 'dev'
}
```

It may very well be CAS that does something wrong. Would it make more sense to create an additional backend, based on the OIDC backend, but which takes this weirdness into account?

**Comment by slyngshede** [comment]
I just notice, that the Patreon backend, while OAuth2, does something similar. 

```
    def get_user_details(self, response):
        details = response["attributes"]
        return {
            "username": details.get("full_name"),
            "email": details.get("email"),
            "fullname": details.get("full_name"),
            "first_name": details.get("first_name"),
            "last_name": details.get("last_name"),
        }
```

It's not exactly the same, but it also need to access the attributes for a "sub-dict".

**Comment by davidhalter** [comment]
> It may very well be CAS that does something wrong. Would it make more sense to create an additional backend, based on the OIDC backend, but which takes this weirdness into account?

I'd personally prefer that. IMO we should not complicate the basic OIDC backend, unless there is clearly a general consensus in the "OIDC community" that things should be that way.

**Comment by slyngshede** [comment]
Will rewrite to a separate backend

**Pull request closed without merging**
