### PR TITLE
Version bump 4.1.0

### PR DESCRIPTION
**Pull request by omab**
## Proposed changes

Release 4.1.0

Changes:

- Discourse backend
- Add `get` and `delete` class methods for `NonceMixin`
- Use stretegies as interface to fetch backends
- Get Apple user first and last name from `self.data`
- Instagram Legacy API has been replaced with Instagram Basic Display API since the first one was deprecated, [see](https://www.instagram.com/developer/).
- Store `expires_in` for Zoom backend

## Types of changes

Please check the type of change your PR introduces:

- [x] Release (new release request)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by omab** [comment]
@python-social-auth/maintainers please review.

**Comment by nijel** [comment]
There are some things missing from the changelog, see https://github.com/python-social-auth/social-core/pull/568

**Comment by omab** [comment]
@nijel #568 approved, I'll rebase this one once those changes are merged.

**Review by nijel — APPROVED** [review]
Otherwise I think it's okay to release.

**Review by abigail1010 — COMMENTED** [review]
social_core/__init__.py

**Pull request merged**
