### PR TITLE
Migrate Twitch v3 → v5 (fix #386)

### LINKED ISSUE #386: Twitch API v3 shutdown
Twitch API v3 shutdown scheduled for September 12, 2019 according to https://dev.twitch.tv/docs/v5/guides/migration/

Authentication domain moved from https://api.twitch.tv/kraken to https://id.twitch.tv

As far as I can see that's all the changes which are related to authentication process.

### PR DESCRIPTION
**Pull request by fedosov**
Resolves #386 
---
Changed authorization and access token URLs also verified and actualised `user_data` structure in test.

### CODE REVIEW

**Comment by fedosov** [comment]
@omab can you kindly check these changes? Twitch shuts down its API v3 on September 12, 2019

**Comment by fedosov** [comment]
Tested these changes on production and added header entry for user data request.

**Comment by omab** [comment]
Thanks!

**Comment by DorkmasterFlek** [comment]
Thank you! When will the new version be released next? The old Twitch API has officially shut down now and the Twitch OAuth does not work with the most recent released version 3.2.0 from back in May.

**Comment by DorkmasterFlek** [comment]
@omab When will the next release of this library be?  The old Twitch API has been shut down for several months and Twitch authentication does not work at all with the current version of this library.  I've been installing it manually from the GitHub repo directly with pip as a workaround.

**Pull request merged**
