### PR TITLE
Bump Facebook Graph API version to version 8.0

### PR DESCRIPTION
**Pull request by Tenzer**
## Proposed changes

This upgrades to the latest version of the API currently available.

Each API version is available for 2 years, and the previous version 3.2 API is
reaching end of life on May 4th, 2021. It would be good to upgrade to a newer
version before then in order to have time to find any version incompatibilities
before the current version is deprecated, although I haven't been able to find
any breaking changes by looking at the version history between the versions:
https://developers.facebook.com/docs/graph-api/changelog

## Types of changes

Please check the type of change your PR introduces:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [x] Other (please describe): Future proofing(?)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Tenzer** [comment]
The test failure seem to be the same as on the master branch, and I would guess it's unrelated to this change.

**Comment by aoghina** [comment]
Good stuff @Tenzer, hope this can be merged soon.

**Comment by omab** [comment]
Manually merged: https://github.com/python-social-auth/social-core/commit/e199ebf49cb4803a2d39e545568b55e747f92ada

**Comment by Tenzer** [comment]
Thanks!

**Pull request closed without merging**
