### PR TITLE
CHANGELOG.md: Fix typo

### PR DESCRIPTION
**Pull request by cclauss**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers
why we should accept this pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue.

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Review by digismack — APPROVED** [review]

**Comment by nijel** [comment]
Thanks. Looks good, we just need to fix the flake8 failures (unrelated to this PR) to allow merging...

**Comment by cclauss** [comment]
> Just need to fix the flake8 failures...

Seems like using psf/black or autoflake would make sense because machines can format code so humans don't have to.

**Comment by nijel** [comment]
Indeed. I use black for most of my projects, but choosing a code formatter here should be agreed by other maintainers as well.

**Comment by cclauss** [comment]
* Add `double-quote-string-fixer` and `end-of-file-fixer` to pre-commit so it autofixes many of flake8's complaints.
* Reformat the 6 files (unrelated to the typo) that were failing the flake8 tests.

**Comment by nijel** [comment]
Can these please be separate pull requests? I've pinned an older version of flake8 in https://github.com/python-social-auth/social-core/pull/702 to fix the CI failure for now, so these can be addressed when upgrading flake8 pin.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
