### PR TITLE
Add SimpleLogin backend

### PR DESCRIPTION
**Pull request by nguyenkims**
SimpleLogin.io is a social login provider that focus on user privacy.

This is my first PR in this project, please let me know if you need any additional information! Another PR will be created in https://github.com/python-social-auth/social-docs to add SimpleLogin doc.

### CODE REVIEW

**Comment by nguyenkims** [comment]
Hi by any chance has anyone had the time to look at this PR?

**Comment by nguyenkims** [comment]
@omab I'm not sure if I should ask you directly like this ... do you know what are the next steps of this PR please 🙏? 

Currently I'm telling my clients to use 
`pip3 install django git+ssh://git@github.com/simple-login/social-core.git@sl` which is not proper at all ...

**Comment by nguyenkims** [comment]
Hi any news on this PR please?

**Comment by omab** [comment]
Merged, thanks!

**Comment by nguyenkims** [comment]
@omab thanks a lot! Do you know when is the next version please? Btw there’s a related PR at https://github.com/python-social-auth/social-docs/pull/64 , could you have a look please?

**Pull request merged**
