### PR TITLE
Pass "next" URL through SAML RelayState

### PR DESCRIPTION
**Pull request by RJPercival**
Passing the "next" URL to redirect to after authentication completes is the primary use case for `RelayState`, but the SAML backend did not previously support this use. Instead, it relied on the `Strategy` to store the "next" URL in session state and restore it from there after login. Unfortunately, in the case of SAML, this does not work if the server has set the session cookie's [`SameSite` attribute](https://owasp.org/www-community/SameSite) to "Lax" or "Strict", as [the SAML POST request from the IdP](https://en.wikipedia.org/wiki/SAML_2.0#SP_redirect_request;_IdP_POST_response) will not contain the session cookie.

The new `RelayState` format (a JSON object) allows for further extensibility, as arbitrary additional fields can be added in the future.

A number of additional SAML response test fixtures have been added - these differ only in the value of the `RelayState` parameter, and are used for testing different values (e.g. missing keys in the JSON).

I've manually tested this with Okta and Django and the redirect works as intended (it previously did not).

### CODE REVIEW

**Review by digismack — APPROVED** [review]

**Comment by digismack** [comment]
Looks good to me. Thanks!

**Comment by RJPercival** [comment]
Looks like I'm not authorized to merge this @digismack.

**Comment by RJPercival** [comment]
@digismack, thanks for merging. Any idea when this will go out in a release?

**Comment by nijel** [comment]
We need a new release soon to address https://github.com/python-social-auth/social-core/issues/854, but it needs to be fixed first…

**Pull request merged**
