### PR TITLE
Update vk backend to the 5.131

### PR DESCRIPTION
**Pull request by ffedoroff**
Update vk backend to the latest api. More info here: https://vk.com/dev/versions

## Proposed changes

Just bump to new version.

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Just bump to new version.

### CODE REVIEW

**Comment by digismack** [comment]
I'm unfamiliar with this particular backend, but the changes look appropriate to me. @alrusdi or @desecho have commits here (years ago) – do either of you have an opinion on this?

**Comment by c0derbug** [comment]
I fully support this fix. All it takes is to update the version in the backend method

**Comment by desecho** [comment]
The change makes sense to me too.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
