### PR TITLE
Added support for ELIXIR AAI

### PR DESCRIPTION
**Pull request by tauceti2**

### CODE REVIEW

**Comment by tauceti2** [comment]
@omab, please can you have a look on failing tests? Our OIDC server will not allow you to do the /authorize via cmdline, because we are using federated authN. Also for we are not by default allow clients to request any scope, scopes are enabled to the clients manually after the approval. Is it possible to pass the test with this configuration?

**Comment by tauceti2** [comment]
Added missing entry into the change log.

**Comment by bgruening** [comment]
@omab can you please have a look at this PR. Thanks.

**Comment by bgruening** [comment]
@omab thanks a lot!

**Pull request merged**
