### PR TITLE
Use passed in access_token rather than the response object - Fix #450

### LINKED ISSUE #450: Azure AD Tenant throws exception "AttributeError: 'NoneType' object has no attribute 'get'"
Attempting to verify Azure AD tenant token

### Expected behaviour

Token verification should succeed

### Actual behaviour

Exception thrown:

AttributeError: 'NoneType' object has no attribute 'get'

### Any other comments?

Comparing the azuread_tenant.py function `user_data` and the azuread.py `user_data` function reveals significant differences.  Specifically, `user_data` in azured.py checks for `response` being `None`.

Using the standard azuread backend in place of the tenant backend is a work-around since there are no tenant-specific keys for token validation

### PR DESCRIPTION
**Pull request by paulw11**
## Proposed changes

Fixes an error "'NoneType' object has no attribute 'get'" when using the azure_tenant backend to validate a JWT.  Fix #450

## Types of changes

Please check the type of change your PR introduces:

- [X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by dacevedo12** [comment]
Thanks! I just had this exact problem. Any change of getting this merged soon? I'll patch it meanwhile

**Comment by omab** [comment]
PR merged manually to add the corresponding changelog entry, but Github fails to pick up the change. Thanks!

**Comment by dacevedo12** [comment]
Oh no, I just realized the reason why azure.py uses that condition. If you auth programatically using an oauth2 token response is None and access token is your JWT. But if you auth through the view then response exists and access token is NOT a JWT.

Welp, this PR fixed one thing while breaking another

**Comment by paulw11** [comment]
So, we need something like:
```Python
 def user_data(self, access_token, *args, **kwargs):
      
    response = kwargs.get('response')
    response_token = response.get('id_token')
    id_token = response_token if response_token else  access_token
         
```

**Pull request closed without merging**
