### PR TITLE
Added backend to support microsoft graph login

### PR DESCRIPTION
**Pull request by leonholub**
Added backend to support login with a user account from login.microsoftonline.com/ using the newer oauth2 v2.0 API to allow access to graph.microsoft.com.

### CODE REVIEW

**Comment by Menda** [comment]
@omab please check

**Comment by omab** [comment]
Merged, thanks!

**Comment by jpatel3** [comment]
Is there steps or instruction on how to use it. I am running into the following error -

https://login.live.com/err.srf?lc=1033#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/.&state=<code>

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

I do have application via applicaiton registratin portal on app.dev.microsoft.com

**Comment by Menda** [comment]
Hi @jpatel3 Firstly, you need an HTTPS endpoint on your side. If you want to test it on localhost, I recommend you to install [ngrok](https://ngrok.com/).

Then after creating your application in  you need to set these variables: 

SOCIAL_AUTH_LOGIN_REDIRECT_URL=/
SOCIAL_AUTH_MICROSOFT_GRAPH_KEY=<YOUR_APP_KEY>
SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL=https://your.url/complete/microsoft-graph
SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET=<YOUR_APP_SECRET>
SOCIAL_AUTH_REDIRECT_IS_HTTPS=True

**Comment by jpatel3** [comment]
Thanks @Menda for steps. I tried above, getting following error - 

`https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=ZEfkLeXtxhnDhyzWqhx3jHkPjTZEaI2g`

Application is registered on https://apps.dev.microsoft.com/
in graph key, I have application id
graph secret, I have Password/Public key from application secret

is that right? or I am configuring it wrong.

**Comment by jpatel3** [comment]
@Menda Ignore the previous comment. It works fine. I had to update the url on microsoft portal after grok. Question - Do we need to specify redirect_uri in django settings? I don't provide for the google settings.

**Comment by Menda** [comment]
Maybe you don't need it. But I'm not sure, just try without it.

**Comment by jpatel3** [comment]
Sure, will try out. Also, another thing I notice is it didn't save email in the user object. Although, in the code, I do see its pulling 'mail' and assigning to 'email' from API. I'll debug and check it.

**Comment by jpatel3** [comment]
@Menda - There is an issue with fetching `email` in this backend. Currently, for `email`, it's trying to read using following - 

```
        return {'username': response.get('displayName', ''),
                'email': response.get('mail'),
                'fullname': response.get('displayName', ''),
                'first_name': response.get('givenName', ''),
                'last_name': response.get('surname', '')}
```
However in the response object, email is in `userPrincipalName` field. I think when the account is not native microsoft one, and created using other domain email, `mail` field is blank and `userPrincipalName` is been used. if `mail` is blank, and `userPrincipalName` is email regex, can we set it as `email` field for the `get_user_details`? What do you think?

**Comment by jpatel3** [comment]
@Menda Any luck reviewing issue? I can make the change if you think the above-suggested way is fine.

**Comment by Menda** [comment]
Hi @jpatel3 I can't check your problem using the Microsoft backend, but feel free to send a patch if you think there is a bug somewhere.

**Comment by jpatel3** [comment]
Submitted here https://github.com/python-social-auth/social-core/pull/176

**Comment by gustavwennerblom** [comment]
I found this backend quite useful - great work! However, it took me some time to get it working since it doesn't seem to be included in the [documentation](https://python-social-auth-docs.readthedocs.io/en/latest/backends/index.html). Am I looking at the wrong place? Would be happy to contribute a draft document if perceived helpful.

**Pull request merged**
