### PR TITLE
Add Facebook Limited Login backend

### PR DESCRIPTION
**Pull request by Tenzer**
## Proposed changes

This adds a new backend for Facebook Limited Login

This is a new login method for Facebook which uses OpenID Connect and doesn't have the ability to associate a user logging into one app with the IDFA token on iOS devices: https://developers.facebook.com/docs/facebook-login/limited-login.

## Types of changes

Please check the type of change your PR introduces:

- [ ] Release (new release request)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by Tenzer** [comment]
I have converted this to a draft while I test it out more thoroughly. It turned out the "simple" approach I was hoping for doesn't quite work since this backend doesn't have any APIs available for validating the user, nonce, etc.

**Comment by Tenzer** [comment]
I have rebased the branch as I noticed there were some conflicts with the master branch. The sole test failure is the same as what is currently in the master branch.

**Comment by nijel** [comment]
Looks good, but can't merge until SAML errors in the tests are sorted out...

**Comment by Tenzer** [comment]
Those SAML tests look pretty broken to me. I just tried to run them locally to have a look at how they are failing, and I managed to run it three times in a row which produced different failures each time. The first run was successful but the two following ones failed with different errors:
https://gist.github.com/Tenzer/12720fc757ec4d595e4b775825ff8323

**Comment by Tenzer** [comment]
@nijel Any chance you could take a look at this PR again? I have rebased it to get the latest fixes in from the master branch, and that seems to have fixed the unrelated failing tests.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by Tenzer** [comment]
Thanks a lot!

**Comment by nijel** [comment]
This has introduced non-declared hard dependency on jose, see https://github.com/python-social-auth/social-app-django/issues/427#issuecomment-1471630584

**Comment by Tenzer** [comment]
Sorry about that! I didn't really think that importing an internal module would cause issues like this.

I guess another solution which wasn't mentioned in your linked comment, would be to move all the imports of `jose` inside `social_core/backends/open_id_connect.py` into the methods where they are used. Then they won't create errors at import time.

Switching everything to use PyJWT would probably be the nicest solution to this, but will likely take more time and be more complicated than other workarounds, such as either always depending on jose or splitting Facebook Limited Login into a separate file.

Is there anything you would like me to do to help out with this?

**Comment by nijel** [comment]
Moving the imports will make the backend fail at authentication time instead of at import time, what sort of hides the configuration error.

**Pull request merged**
